// Interactive Brokers exchange codes are not available in the API (according to support).
// This type is derived from https://www.interactivebrokers.com/en/trading/products-exchanges.php#/exchanges
// The link uses an undocumented but public endpoint to fetch exchange codes.
// Endpoint: https://www.interactivebrokers.com/webrest/exchanges/search/
// Request payload includes country codes, pagination, and sorting options.

import { enums, type GuardType } from 'https://raw.githubusercontent.com/systematic-trader/type-guard/main/mod.ts'

export const ExchangeCodeValues = [
  // #region From https://www.interactivebrokers.com/webrest/exchanges/search/
  'AEB',
  'AEQLIT',
  'AMEX',
  'APEXEN',
  'APEXIT',
  'AQEUAT',
  'AQEUDE',
  'AQEUDK',
  'AQEUEN',
  'AQEUES',
  'AQEUIT',
  'AQXECH',
  'AQXEUK',
  'ARCA',
  'ARCAEDGE',
  'ASX',
  'ASXCEN',
  'BATECH',
  'BATEDE',
  'BATEEN',
  'BATEES',
  'BATEIT',
  'BATEUK',
  'BATS',
  'BELFOX',
  'BEX',
  'BM',
  'BOVESPA',
  'BOX',
  'BURSAMY',
  'BUX',
  'BVL',
  'BVME',
  'BVME.ETF',
  'BYX',
  'CBOE',
  'CBOE.JPN',
  'CBOE2',
  'CBOT',
  'CDE',
  'CEDX',
  'CFE',
  'CFETAS',
  'CHIXAU',
  'CHIXCH',
  'CHIXDE',
  'CHIXEN',
  'CHIXES',
  'CHIXIT',
  'CHIXUK',
  'CHX',
  'CME',
  'COMEX',
  'CPH',
  'DRCTEDGE',
  'DXEAT',
  'DXEDE',
  'DXEDK',
  'DXEEN',
  'DXEES',
  'DXEIT',
  'EBS',
  'EDGEA',
  'EDGX',
  'EMERALD',
  'ENDEX',
  'ENEXT.BE',
  'EUREX',
  'EUREXUK',
  'EURONEXT',
  'FTA',
  'FUNDSERV',
  'FWB',
  'GEMINI',
  'GETTEX',
  'HKFE',
  'IBBOND',
  'IBCMDTY',
  'IBDESK',
  'IBEOS',
  'IBFX',
  'IBIS',
  'IBKRAM',
  'IBKRATS',
  'IBUSCFD',
  'ICEEU',
  'ICEEUSOFT',
  'ICEUS',
  'IDEALPRO',
  'IDEM',
  'IEX',
  'IPE',
  'ISE',
  'ISED',
  'ISLAND',
  'JPNNEXT',
  'JSE',
  'KSE',
  'LMEOTC',
  'LSE',
  'LSEETF',
  'LSEIOB1',
  'LTSE',
  'MATIF',
  'MEFFRV',
  'MEMX',
  'MERCURY',
  'MEXDER',
  'MEXI',
  'MIAX',
  'MONEP',
  'N.RIGA',
  'N.TALLINN',
  'N.VILNIUS',
  'NASDAQ',
  'NASDAQBX',
  'NASDAQOM',
  'NSE',
  'NYBOT',
  'NYMEX',
  'NYSE',
  'NYSEFLOOR',
  'NYSELIFFE',
  'NYSENAT',
  'OMS',
  'OMXNO',
  'OSE',
  'OSE.JPN',
  'OSL',
  'OTCLNKECN',
  'OVERNIGHT',
  'PAXOS',
  'PEARL',
  'PHLX',
  'PINK',
  'PRA',
  'PSE',
  'PSX',
  'SBF',
  'SEHK',
  'SEHKSTAR',
  'SFB',
  'SGX',
  'SGXCME',
  'SMFE',
  'SNFE',
  'SWB',
  'TADAWUL',
  'TASE',
  'TGATE',
  'TGHEAT',
  'TGHEDE',
  'TGHEDK',
  'TGHEEN',
  'TGHEES',
  'TGHEIT',
  'TRADEWEB',
  'TRQXCH',
  'TRQXDE',
  'TRQXEN',
  'TRQXES',
  'TRQXUK',
  'TRWBCH',
  'TRWBDE',
  'TRWBEN',
  'TRWBIT',
  'TRWBSE',
  'TRWBUK',
  'TRWBUKETF',
  'TSE',
  'TSE.JPN',
  'TSEJ',
  'TWSE',
  'VENTURE',
  'VSE',
  'WSE',
  'ZEROHASH',
  // #endregion

  // #region Found while using different endpoints
  'HEX',
  'AEB',
  'IBIS2',
  'FWB2',
  'SWB2',
  'GETTEX2',
  'EUIBSI',
  'FOXRIVER',
  'TPLUS0',
  'NMS',
  'SCM',
  'OTC',
  'BONDDESKG',
  // #endregion

  // Finally, IB has a "SMART" exchange, which is a special exchange that allows IB to route orders to the best exchange
  'SMART',
] as const

// Has been derived from the endpoint
// But there are some missing exchange codes, such as IBIS2 (there is both an IBIS and an IBIS2).
// More will be added as we find them.
export const ExchangeCode = enums(ExchangeCodeValues)

export type ExchangeCode = GuardType<typeof ExchangeCode>
